/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Alfred-PC
 */
public class MembresiasMiemb extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public MembresiasMiemb() {
        initComponents();
        setTitle("Agregar miembro");
        setDefaultCloseOperation(MembresiasMiemb.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBgAgrMemb = new javax.swing.JPanel();
        lblAgMembresia = new javax.swing.JLabel();
        paneFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        scrolltMembresias = new javax.swing.JScrollPane();
        tableMembresias = new javax.swing.JTable();
        lblnicio = new javax.swing.JLabel();
        dateComienzo = new com.toedter.calendar.JDateChooser();
        btnAgregarMemb = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblIDMiemb = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombreMiemb = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblApellidosMiemb = new javax.swing.JLabel();
        btnEliminarMemb = new javax.swing.JButton();
        btnPagarMemb = new javax.swing.JButton();
        scrolltRegMemb = new javax.swing.JScrollPane();
        tableRegistroMemb = new javax.swing.JTable();
        lblScratchAgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneBgAgrMemb.setBackground(new java.awt.Color(29, 29, 29));
        paneBgAgrMemb.setLayout(null);

        lblAgMembresia.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        lblAgMembresia.setForeground(new java.awt.Color(255, 255, 255));
        lblAgMembresia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgMembresia.setText("Membresias del miembro ");
        paneBgAgrMemb.add(lblAgMembresia);
        lblAgMembresia.setBounds(270, 20, 260, 24);

        javax.swing.GroupLayout paneFotoLayout = new javax.swing.GroupLayout(paneFoto);
        paneFoto.setLayout(paneFotoLayout);
        paneFotoLayout.setHorizontalGroup(
            paneFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        paneFotoLayout.setVerticalGroup(
            paneFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        paneBgAgrMemb.add(paneFoto);
        paneFoto.setBounds(290, 60, 150, 150);

        tableMembresias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Membresias"
            }
        ));
        scrolltMembresias.setViewportView(tableMembresias);

        paneBgAgrMemb.add(scrolltMembresias);
        scrolltMembresias.setBounds(460, 60, 310, 150);

        lblnicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblnicio.setForeground(new java.awt.Color(255, 255, 255));
        lblnicio.setText("Inicio:");
        paneBgAgrMemb.add(lblnicio);
        lblnicio.setBounds(460, 220, 50, 30);
        paneBgAgrMemb.add(dateComienzo);
        dateComienzo.setBounds(510, 220, 80, 30);

        btnAgregarMemb.setBackground(new java.awt.Color(0, 51, 51));
        btnAgregarMemb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarMemb.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMemb.setText("Agregar membresia");
        paneBgAgrMemb.add(btnAgregarMemb);
        btnAgregarMemb.setBounds(600, 220, 170, 30);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back_icon.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        paneBgAgrMemb.add(lblBack);
        lblBack.setBounds(30, 52, 35, 35);

        lblID.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        paneBgAgrMemb.add(lblID);
        lblID.setBounds(90, 70, 70, 17);

        lblIDMiemb.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        lblIDMiemb.setForeground(new java.awt.Color(255, 255, 255));
        lblIDMiemb.setText("-");
        paneBgAgrMemb.add(lblIDMiemb);
        lblIDMiemb.setBounds(90, 90, 180, 20);

        lblNombre.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        paneBgAgrMemb.add(lblNombre);
        lblNombre.setBounds(90, 120, 70, 17);

        lblNombreMiemb.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        lblNombreMiemb.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreMiemb.setText("-");
        paneBgAgrMemb.add(lblNombreMiemb);
        lblNombreMiemb.setBounds(90, 140, 180, 20);

        lblApellidos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("Apellidos");
        paneBgAgrMemb.add(lblApellidos);
        lblApellidos.setBounds(90, 170, 80, 17);

        lblApellidosMiemb.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        lblApellidosMiemb.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidosMiemb.setText("-");
        paneBgAgrMemb.add(lblApellidosMiemb);
        lblApellidosMiemb.setBounds(90, 190, 70, 20);

        btnEliminarMemb.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarMemb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEliminarMemb.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMemb.setText("Eliminar membresia");
        paneBgAgrMemb.add(btnEliminarMemb);
        btnEliminarMemb.setBounds(600, 280, 160, 30);

        btnPagarMemb.setBackground(new java.awt.Color(0, 0, 51));
        btnPagarMemb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPagarMemb.setForeground(new java.awt.Color(255, 255, 255));
        btnPagarMemb.setText("Pagar membresia");
        paneBgAgrMemb.add(btnPagarMemb);
        btnPagarMemb.setBounds(430, 280, 150, 30);

        tableRegistroMemb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha de inicio", "Tipo de membresia", "Vencimiento", "Precio", "Fecha de creación", "Estado de membresia"
            }
        ));
        scrolltRegMemb.setViewportView(tableRegistroMemb);

        paneBgAgrMemb.add(scrolltRegMemb);
        scrolltRegMemb.setBounds(30, 320, 740, 250);

        lblScratchAgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/scratchtwo.png"))); // NOI18N
        paneBgAgrMemb.add(lblScratchAgr);
        lblScratchAgr.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBgAgrMemb, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBgAgrMemb, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MembresiasMiemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MembresiasMiemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MembresiasMiemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MembresiasMiemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MembresiasMiemb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMemb;
    private javax.swing.JButton btnEliminarMemb;
    private javax.swing.JButton btnPagarMemb;
    private com.toedter.calendar.JDateChooser dateComienzo;
    private javax.swing.JLabel lblAgMembresia;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidosMiemb;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDMiemb;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreMiemb;
    private javax.swing.JLabel lblScratchAgr;
    private javax.swing.JLabel lblnicio;
    private javax.swing.JPanel paneBgAgrMemb;
    private javax.swing.JPanel paneFoto;
    private javax.swing.JScrollPane scrolltMembresias;
    private javax.swing.JScrollPane scrolltRegMemb;
    private javax.swing.JTable tableMembresias;
    private javax.swing.JTable tableRegistroMemb;
    // End of variables declaration//GEN-END:variables
}
