/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Alfred-PC
 */
public class Pago extends javax.swing.JFrame {

    /**
     * Creates new form Pago
     */
    public Pago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBgPago = new javax.swing.JPanel();
        lblPagoMemb = new javax.swing.JLabel();
        btnReimprimir = new javax.swing.JButton();
        panePago = new javax.swing.JPanel();
        lblEstadoPago = new javax.swing.JLabel();
        lbImporte = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        btnAgregarMemb = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        lblFechaAc = new javax.swing.JLabel();
        lblFechaDia = new javax.swing.JLabel();
        lblTipoMemb = new javax.swing.JLabel();
        lblNombreMiemb = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblPrecioMemb = new javax.swing.JLabel();
        lblScratchAgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneBgPago.setBackground(new java.awt.Color(29, 29, 29));
        paneBgPago.setLayout(null);

        lblPagoMemb.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        lblPagoMemb.setForeground(new java.awt.Color(255, 255, 255));
        lblPagoMemb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagoMemb.setText("Pago de membresia");
        paneBgPago.add(lblPagoMemb);
        lblPagoMemb.setBounds(0, 20, 500, 24);

        btnReimprimir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnReimprimir.setText("Reimprimir ticket");
        paneBgPago.add(btnReimprimir);
        btnReimprimir.setBounds(170, 340, 160, 30);

        panePago.setBackground(new java.awt.Color(0, 0, 0));

        lblEstadoPago.setBackground(new java.awt.Color(255, 255, 255));
        lblEstadoPago.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblEstadoPago.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoPago.setText("SIN PAGAR");

        javax.swing.GroupLayout panePagoLayout = new javax.swing.GroupLayout(panePago);
        panePago.setLayout(panePagoLayout);
        panePagoLayout.setHorizontalGroup(
            panePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePagoLayout.createSequentialGroup()
                .addComponent(lblEstadoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panePagoLayout.setVerticalGroup(
            panePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePagoLayout.createSequentialGroup()
                .addComponent(lblEstadoPago, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneBgPago.add(panePago);
        panePago.setBounds(260, 120, 210, 40);

        lbImporte.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lbImporte.setForeground(new java.awt.Color(255, 255, 255));
        lbImporte.setText("Importe:");
        paneBgPago.add(lbImporte);
        lbImporte.setBounds(90, 230, 60, 30);

        txtImporte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        paneBgPago.add(txtImporte);
        txtImporte.setBounds(160, 230, 100, 30);

        btnAgregarMemb.setBackground(new java.awt.Color(0, 51, 51));
        btnAgregarMemb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarMemb.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMemb.setText("Agregar pago");
        paneBgPago.add(btnAgregarMemb);
        btnAgregarMemb.setBounds(340, 280, 130, 30);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back_icon.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        paneBgPago.add(lblBack);
        lblBack.setBounds(30, 52, 35, 35);

        lblFechaAc.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblFechaAc.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaAc.setText("Fecha actual");
        paneBgPago.add(lblFechaAc);
        lblFechaAc.setBounds(90, 70, 90, 17);

        lblFechaDia.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        lblFechaDia.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaDia.setText("-");
        paneBgPago.add(lblFechaDia);
        lblFechaDia.setBounds(90, 90, 150, 20);

        lblTipoMemb.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblTipoMemb.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoMemb.setText("Tipo de membresia");
        paneBgPago.add(lblTipoMemb);
        lblTipoMemb.setBounds(90, 120, 140, 17);

        lblNombreMiemb.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        lblNombreMiemb.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreMiemb.setText("-");
        paneBgPago.add(lblNombreMiemb);
        lblNombreMiemb.setBounds(90, 140, 150, 20);

        lblPrecio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("Precio");
        paneBgPago.add(lblPrecio);
        lblPrecio.setBounds(90, 170, 80, 17);

        lblPrecioMemb.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        lblPrecioMemb.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioMemb.setText("-");
        paneBgPago.add(lblPrecioMemb);
        lblPrecioMemb.setBounds(90, 190, 150, 20);

        lblScratchAgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/scratchtwo.png"))); // NOI18N
        paneBgPago.add(lblScratchAgr);
        lblScratchAgr.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBgPago, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBgPago, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMemb;
    private javax.swing.JButton btnReimprimir;
    private javax.swing.JLabel lbImporte;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblEstadoPago;
    private javax.swing.JLabel lblFechaAc;
    private javax.swing.JLabel lblFechaDia;
    private javax.swing.JLabel lblNombreMiemb;
    private javax.swing.JLabel lblPagoMemb;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioMemb;
    private javax.swing.JLabel lblScratchAgr;
    private javax.swing.JLabel lblTipoMemb;
    private javax.swing.JPanel paneBgPago;
    private javax.swing.JPanel panePago;
    private javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
