/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Alfred-PC
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Membresias
     */
    public Usuarios() {
        initComponents();
        setTitle("Usuarios");
        setDefaultCloseOperation(Usuarios.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBgAgr = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblNomUsu = new javax.swing.JLabel();
        txtNomUsu = new javax.swing.JTextField();
        lblConUsu = new javax.swing.JLabel();
        txtConUsu = new javax.swing.JTextField();
        lblTipoUsu = new javax.swing.JLabel();
        cboxTipo = new javax.swing.JComboBox<>();
        scrolltUsuarios = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btnEliminarUsu = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        lblScratchAgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneBgAgr.setBackground(new java.awt.Color(29, 29, 29));
        paneBgAgr.setLayout(null);

        lblUsuarios.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setText("Usuarios");
        paneBgAgr.add(lblUsuarios);
        lblUsuarios.setBounds(0, 20, 800, 24);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back_icon.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        paneBgAgr.add(lblBack);
        lblBack.setBounds(30, 52, 35, 35);

        lblNomUsu.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNomUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblNomUsu.setText("Nombre de usuario");
        paneBgAgr.add(lblNomUsu);
        lblNomUsu.setBounds(90, 70, 130, 17);

        txtNomUsu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        paneBgAgr.add(txtNomUsu);
        txtNomUsu.setBounds(90, 90, 330, 30);

        lblConUsu.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblConUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblConUsu.setText("Contraseña de usuario");
        paneBgAgr.add(lblConUsu);
        lblConUsu.setBounds(90, 130, 190, 17);

        txtConUsu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        paneBgAgr.add(txtConUsu);
        txtConUsu.setBounds(90, 150, 330, 30);

        lblTipoUsu.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblTipoUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoUsu.setText("Tipo de usuario");
        paneBgAgr.add(lblTipoUsu);
        lblTipoUsu.setBounds(90, 190, 140, 17);

        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador" }));
        paneBgAgr.add(cboxTipo);
        cboxTipo.setBounds(90, 210, 130, 30);

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuarios"
            }
        ));
        scrolltUsuarios.setViewportView(tableUsuarios);

        paneBgAgr.add(scrolltUsuarios);
        scrolltUsuarios.setBounds(470, 70, 300, 300);

        btnEliminarUsu.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarUsu.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEliminarUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsu.setText("Eliminar usuario");
        paneBgAgr.add(btnEliminarUsu);
        btnEliminarUsu.setBounds(630, 380, 140, 30);

        btnCrear.setBackground(new java.awt.Color(0, 51, 51));
        btnCrear.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear usuario");
        paneBgAgr.add(btnCrear);
        btnCrear.setBounds(90, 380, 120, 30);

        lblScratchAgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/scratchtwo.png"))); // NOI18N
        paneBgAgr.add(lblScratchAgr);
        lblScratchAgr.setBounds(0, 0, 800, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBgAgr, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBgAgr, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminarUsu;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblConUsu;
    private javax.swing.JLabel lblNomUsu;
    private javax.swing.JLabel lblScratchAgr;
    private javax.swing.JLabel lblTipoUsu;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel paneBgAgr;
    private javax.swing.JScrollPane scrolltUsuarios;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField txtConUsu;
    private javax.swing.JTextField txtNomUsu;
    // End of variables declaration//GEN-END:variables
}
